version: '3.8'

services:
  mindguru-dev:
    build: 
      context: .
      target: development
    container_name: mindguru-dev
    ports:
      - "5173:5173"
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - VITE_GROQ_API_KEY=${VITE_GROQ_API_KEY}
    networks:
      - mindguru_network

networks:
  mindguru_network:
    driver: bridge